/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Form.FormInAdmin.NhanVienJPanel;
import Form.FormInAdmin.TaiKhoanJPaneal;
import ChuyenCanh.ChuyenController;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class AdminJPanel extends javax.swing.JPanel {

    static String nameColor = "#F5CBA7";
    static String nameColorSelected = "#E67E22";
    /**
     * Creates new form AdminJPanel
     */
    public AdminJPanel() {
        initComponents();
        
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(MainSection);
        controller.setView(new TaiKhoanJPaneal(), TKButton, nameColorSelected);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainSection = new javax.swing.JPanel();
        ButtonSection = new javax.swing.JPanel();
        NVButton = new javax.swing.JButton();
        TKButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        MainSection.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout MainSectionLayout = new javax.swing.GroupLayout(MainSection);
        MainSection.setLayout(MainSectionLayout);
        MainSectionLayout.setHorizontalGroup(
            MainSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MainSectionLayout.setVerticalGroup(
            MainSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(MainSection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ButtonSection.setBackground(new java.awt.Color(255, 255, 255));

        NVButton.setBackground(Color.decode("#F5CBA7"));
        NVButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NVButton.setText(" NHÂN VIÊN");
        NVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVButtonActionPerformed(evt);
            }
        });

        TKButton.setBackground(Color.decode("#F5CBA7"));
        TKButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TKButton.setText("TÀI KHOẢN ĐĂNG NHẬP");
        TKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonSectionLayout = new javax.swing.GroupLayout(ButtonSection);
        ButtonSection.setLayout(ButtonSectionLayout);
        ButtonSectionLayout.setHorizontalGroup(
            ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonSectionLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(TKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(146, 146, 146)
                .addComponent(NVButton, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );
        ButtonSectionLayout.setVerticalGroup(
            ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonSectionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NVButton, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(TKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ButtonSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(MainSection);
        controller.setView(new TaiKhoanJPaneal(), TKButton, nameColorSelected);
    }//GEN-LAST:event_TKButtonActionPerformed

    private void NVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(MainSection);
        controller.setView(new NhanVienJPanel(), NVButton, nameColorSelected);
    }//GEN-LAST:event_NVButtonActionPerformed
    
    void DefaultColorButton()
    {
        NVButton.setBackground(Color.decode(nameColor));
        TKButton.setBackground(Color.decode(nameColor));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonSection;
    private javax.swing.JPanel MainSection;
    private javax.swing.JButton NVButton;
    private javax.swing.JButton TKButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
