/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import ThongTin.DanhSachSanPham;
import ThongTin.DonViTinh;
import ThongTin.LoaiSanPham;
import ThongTin.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class SanPhamJPanel extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    DefaultTableModel tableModelTK;
    List <SanPham> sanphamList = new ArrayList<>();
    /**
     * Creates new form SanPhamJPanel
     */
    
    public SanPhamJPanel() {
        initComponents();
        SetupLoaiSanPham();
        SetupDonViTinh();
        tableModel = (DefaultTableModel) tblBANGSP.getModel();
        tableModelTK =(DefaultTableModel) tblBangTimKiem.getModel();
        showSanPham();
    }
    private void showSanPham()
    {
        //sanphamList = DanhSachSanPham.getInstance().getsanphamList();
        sanphamList = new DanhSachSanPham().getInstance().getDanhSachSP();
        tableModel = (DefaultTableModel) tblBANGSP.getModel();
        tblBANGSP.setModel(tableModel);
        
        for(int i=0; i< sanphamList.size();i++)
        {
            Object[] row =new Object[6];
            row[0]=sanphamList.get(i).getMaSanPham();
            row[1]=sanphamList.get(i).getTenSanPham();
            row[2]=sanphamList.get(i).getSoLuong();
            row[3]=sanphamList.get(i).getLoaiSanPham();
            row[4]=sanphamList.get(i).getDonViTinh();
            row[5]=sanphamList.get(i).getGia();
            
            tableModel.addRow(row);
        }
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        btnThemsp = new javax.swing.JButton();
        btnxoasp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        cbDVT = new javax.swing.JComboBox<>();
        cbLoaiSP = new javax.swing.JComboBox<>();
        btnSua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBANGSP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangTimKiem = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ SẢN PHẨM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setForeground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NHAP TT SP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setText("MÃ SẢN PHẨM");

        jLabel2.setText("TÊN SẢN PHẨM");

        jLabel3.setText("LOẠI SẢN PHẨM");

        jLabel4.setText("ĐƠN VỊ TÍNH");

        jLabel5.setText("ĐƠN GIÁ");

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        btnThemsp.setText("THÊM");
        btnThemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemspActionPerformed(evt);
            }
        });

        btnxoasp.setText("XÓA");
        btnxoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaspActionPerformed(evt);
            }
        });

        jLabel7.setText("SỐ LƯỢNG");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        cbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiSPActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblBANGSP.setBackground(new java.awt.Color(204, 204, 255));
        tblBANGSP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblBANGSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SẢN PHẨM", "TÊN SẢN PHẨM", "SỐ LƯỢNG", "LOẠI SẢN PHẨM", "ĐƠN VỊ TÍNH", "ĐƠN GIÁ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBANGSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBANGSPMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblBANGSPMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblBANGSP);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIM KIEM SP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        tblBangTimKiem.setBackground(new java.awt.Color(204, 204, 255));
        tblBangTimKiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SẢN PHẨM", "TÊN SẢN PHẨM", "SỐ LƯỢNG", "LOẠI SẢN PHẨM", "ĐƠN VỊ TÍNH", "ĐƠN GIÁ"
            }
        ));
        jScrollPane1.setViewportView(tblBangTimKiem);

        btnTimKiem.setText("TÌM KIẾM");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnTimKiem)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
        );

        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLoaiSP, 0, 230, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(cbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(137, 137, 137)
                .addComponent(btnThemsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(195, 195, 195)
                .addComponent(btnxoasp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106)
                .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoasp)
                    .addComponent(btnSua)
                    .addComponent(btnThemsp)
                    .addComponent(Reset))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("NHAP THÔNG TIN SẢN PHẨM");
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemspActionPerformed
        // TODO add your handling code here:
        String MaSanPham= txtMaSP.getText();
        String TenSanPham =txtTenSP.getText();
        int SoLuong = Integer.parseInt(txtSoLuong.getText());
        String LoaiSanPham = cbLoaiSP.getSelectedItem().toString() ;
        String DonViTinh = cbDVT.getSelectedItem().toString();
        int DonGia = Integer.parseInt(txtDonGia.getText());
        
        //SanPham sp = new SanPham (MaSanPham, TenSanPham, SoLuong, LoaiSanPham, DonViTinh, DonGia);
        if (MaSanPham.length()>0&& TenSanPham.length()>0)
        {
           new DanhSachSanPham().getInstance().Insert(MaSanPham, TenSanPham, SoLuong, LoaiSanPham, DonGia, DonViTinh);
           
        } else {
            JOptionPane.showMessageDialog(null," Không được bỏ trống ","Thông báo", JOptionPane.ERROR_MESSAGE);
        }
            
        Refersh();
        
    }//GEN-LAST:event_btnThemspActionPerformed

    private void btnxoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaspActionPerformed
        // TODO add your handling code here:
        String MaSanPham= txtMaSP.getText();
        int option = JOptionPane.showConfirmDialog(this," Bạn Có Muốn Xóa Không?");
        if(option== JOptionPane.YES_OPTION)
        {
            new DanhSachSanPham().getInstance().Delete(MaSanPham);
            Refersh();  
        }

        
    }//GEN-LAST:event_btnxoaspActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        sanphamList = new DanhSachSanPham().getInstance().getDanhSachSP();
        tableModel = (DefaultTableModel) tblBangTimKiem.getModel();
        
        DefaultTableModel model = (DefaultTableModel) tblBangTimKiem.getModel();

        while (model.getRowCount() != 0)
        {
            model.removeRow(0);

        }
        
        tblBangTimKiem.setModel(tableModel);
        Object[] row =new Object[6];
        for(int i=0; i< sanphamList.size();i++)
        {
            if (sanphamList.get(i).getMaSanPham().indexOf(txtTimKiem.getText().toUpperCase()) != -1 || sanphamList.get(i).getTenSanPham().indexOf(txtTimKiem.getText().toUpperCase()) != -1 )
            {
                row[0]= sanphamList.get(i).getMaSanPham();
                row[1]=sanphamList.get(i).getTenSanPham();
                row[2]=sanphamList.get(i).getSoLuong();
                row[3]=sanphamList.get(i).getLoaiSanPham();
                row[4]=sanphamList.get(i).getDonViTinh();
                row[5]=sanphamList.get(i).getGia();
                tableModel.addRow(row);
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void tblBANGSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBANGSPMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_tblBANGSPMouseClicked

    private void cbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoaiSPActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String MaSanPham= txtMaSP.getText();
        String TenSanPham =txtTenSP.getText();
        int SoLuong = Integer.parseInt(txtSoLuong.getText());
        String LoaiSanPham = cbLoaiSP.getSelectedItem().toString() ;
        String DonViTinh = cbDVT.getSelectedItem().toString();
        int DonGia = Integer.parseInt(txtDonGia.getText());
        
        new DanhSachSanPham().getInstance().Update(MaSanPham, TenSanPham, SoLuong, LoaiSanPham, DonGia, DonViTinh);
        Refersh();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        txtMaSP.setText("");
        txtDonGia.setText("");
        txtSoLuong.setText("");
        txtTenSP.setText("");
        cbLoaiSP.setSelectedIndex(0);
        cbDVT.setSelectedIndex(0);
    }//GEN-LAST:event_ResetActionPerformed

    private void tblBANGSPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBANGSPMouseReleased
        // TODO add your handling code here:
        int i = tblBANGSP.getSelectedRow();
        tableModel = (DefaultTableModel) tblBANGSP.getModel();
        txtMaSP.setText(tableModel.getValueAt(i, 0).toString());
        txtTenSP.setText(tableModel.getValueAt(i, 1).toString());
        txtSoLuong.setText(tableModel.getValueAt(i,2 ).toString());
        
        String LoaiSanPham = tableModel.getValueAt(i, 3).toString();
        cbLoaiSP.setSelectedItem(LoaiSanPham);
        
        String donvitinh= tableModel.getValueAt(i, 4).toString();
        cbDVT.setSelectedItem(donvitinh);
        
        txtDonGia.setText(tableModel.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tblBANGSPMouseReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblBangTimKiem.getModel();

        while (model.getRowCount() != 0)
        {
            model.removeRow(0);

        }
        
    }//GEN-LAST:event_btnResetActionPerformed

    
    
    void SetupLoaiSanPham()
    {
        for (int i =0; i< LoaiSanPham.values().length;i++)
        {
            cbLoaiSP.addItem(LoaiSanPham.values()[i].toString());
        }
    }
    
    void SetupDonViTinh()
    {
        for (int i =0; i< DonViTinh.values().length;i++)
        {
            cbDVT.addItem(DonViTinh.values()[i].toString());
        }
    }
    
    void ClearTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblBANGSP.getModel();

        while (model.getRowCount() != 0)
        {
            model.removeRow(0);

        }
    }
    
    void Refersh()
    {
        ClearTable();
        showSanPham();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemsp;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnxoasp;
    private javax.swing.JComboBox<String> cbDVT;
    private javax.swing.JComboBox<String> cbLoaiSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBANGSP;
    private javax.swing.JTable tblBangTimKiem;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

  
}
