/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import ChuyenCanh.ChuyenController;
import Form.AdminJPanel;
import Form.NhaCungCapJPanel;
import Form.PhieuNhapJPanel;
import Form.SanPhamJPanel;
import Form.ThongKeJPanel;
import Form.TrangChuJPanel;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {

    String nameColor = "#85C1E9";
    String nameColorSelected = "#2980B9";
    public static Boolean AdminControl= true;
    
    public static Main Instance = null;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(jPanelView);
        controller.setView(new TrangChuJPanel(),TrangChuButton,nameColorSelected);
        
        Instance = this;
        
        if (AdminControl)
        {
            AdminButton.setEnabled(true);
        }
        else AdminButton.setEnabled(false);
        
    }
    
    public static Main getInstance()
    {
        if (Instance == null)
            Instance = new Main();
        
        return Instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        LogOutButton = new javax.swing.JButton();
        AdminButton = new javax.swing.JButton();
        SanPhamButton = new javax.swing.JButton();
        NhaCungCapButton = new javax.swing.JButton();
        ThongKeButton = new javax.swing.JButton();
        TrangChuButton = new javax.swing.JButton();
        PhieuNhapButton = new javax.swing.JButton();
        jPanelView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÍ SẢN PHẨM CỬA HÀNG TIỆN LỢI");
        setBackground(new java.awt.Color(255, 102, 102));

        jPanelTitle.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ SẢN PHẨM CỬA HÀNG TIỆN LỢI");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1601, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelMenu.setBackground(new java.awt.Color(102, 102, 102));

        LogOutButton.setBackground(new java.awt.Color(102, 255, 204));
        LogOutButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        LogOutButton.setText("LOG OUT");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        AdminButton.setBackground(Color.decode("#5DADE2"));
        AdminButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/baseline_account_circle_black_18dp.png"))); // NOI18N
        AdminButton.setText("ADMIN");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        SanPhamButton.setBackground(Color.decode("#5DADE2"));
        SanPhamButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SanPhamButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/baseline_table_rows_black_18dp.png"))); // NOI18N
        SanPhamButton.setText("KHO SẢN PHẨM");
        SanPhamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanPhamButtonActionPerformed(evt);
            }
        });

        NhaCungCapButton.setBackground(Color.decode("#5DADE2"));
        NhaCungCapButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NhaCungCapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/baseline_house_black_18dp.png"))); // NOI18N
        NhaCungCapButton.setText("NHÀ CUNG CẤP");
        NhaCungCapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhaCungCapButtonActionPerformed(evt);
            }
        });

        ThongKeButton.setBackground(Color.decode("#5DADE2"));
        ThongKeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ThongKeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/baseline_insert_chart_black_18dp.png"))); // NOI18N
        ThongKeButton.setText("THỐNG KÊ");
        ThongKeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeButtonActionPerformed(evt);
            }
        });

        TrangChuButton.setBackground(Color.decode("#5DADE2"));
        TrangChuButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TrangChuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/baseline_home_black_18dp.png"))); // NOI18N
        TrangChuButton.setText("TRANG CHỦ");
        TrangChuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrangChuButtonActionPerformed(evt);
            }
        });

        PhieuNhapButton.setBackground(Color.decode("#5DADE2"));
        PhieuNhapButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PhieuNhapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/notes.png"))); // NOI18N
        PhieuNhapButton.setText("PHIẾU NHẬP");
        PhieuNhapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhieuNhapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrangChuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongKeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SanPhamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhieuNhapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TrangChuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ThongKeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(NhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(SanPhamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(PhieuNhapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(AdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelView.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        try {
            // TODO add your handling code here:
            new Login().show();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
    }//GEN-LAST:event_LogOutButtonActionPerformed

    //nút admin
    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();

        ChuyenController controller = new ChuyenController(jPanelView);
        controller.setView(new AdminJPanel(),AdminButton,nameColorSelected);
    }//GEN-LAST:event_AdminButtonActionPerformed

    //nút vào kho sản phẩm
    private void SanPhamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanPhamButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(jPanelView);
        controller.setView(new SanPhamJPanel(),SanPhamButton,nameColorSelected);
    }//GEN-LAST:event_SanPhamButtonActionPerformed
    
    //nút xem nhà cung cấp
    private void NhaCungCapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhaCungCapButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(jPanelView);
        controller.setView(new NhaCungCapJPanel(),NhaCungCapButton,nameColorSelected);
    }//GEN-LAST:event_NhaCungCapButtonActionPerformed

    //nút xem thống kê
    private void ThongKeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(jPanelView);
        controller.setView(new ThongKeJPanel(),ThongKeButton,nameColorSelected);
    }//GEN-LAST:event_ThongKeButtonActionPerformed

    private void TrangChuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrangChuButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(jPanelView);
        controller.setView(new TrangChuJPanel(),TrangChuButton,nameColorSelected);
    }//GEN-LAST:event_TrangChuButtonActionPerformed

    private void PhieuNhapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhieuNhapButtonActionPerformed
        // TODO add your handling code here:
        DefaultColorButton();
        ChuyenController controller = new ChuyenController(jPanelView);
        controller.setView(new PhieuNhapJPanel(),PhieuNhapButton,nameColorSelected);
    }//GEN-LAST:event_PhieuNhapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Main().setVisible(true);
                new Main().setResizable(false);                                                              
            }
        });
        
        
    }    

    
    public void DefaultColorButton()
    {
        AdminButton.setBackground(Color.decode(nameColor));
        NhaCungCapButton.setBackground(Color.decode(nameColor));
        SanPhamButton.setBackground(Color.decode(nameColor));
        ThongKeButton.setBackground(Color.decode(nameColor));
        TrangChuButton.setBackground(Color.decode(nameColor));
        PhieuNhapButton.setBackground(Color.decode(nameColor));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton NhaCungCapButton;
    private javax.swing.JButton PhieuNhapButton;
    private javax.swing.JButton SanPhamButton;
    private javax.swing.JButton ThongKeButton;
    private javax.swing.JButton TrangChuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPanel jPanelView;
    // End of variables declaration//GEN-END:variables
}


