/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form.FormInAdmin;

import ThongTin.DanhSachTK;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ASUS
 */
public class TaiKhoanJPaneal extends javax.swing.JPanel {

    public Boolean find = false;
    public static TaiKhoanJPaneal Instance = null;



    public static TaiKhoanJPaneal getInstance() {
        if (Instance == null)
            Instance = new TaiKhoanJPaneal();
        
        return Instance;
    }
    public TaiKhoanJPaneal() {
        initComponents();

        TableColumn column = TableUser.getColumnModel().getColumn(0);
        column.setPreferredWidth(20);
        
        
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FindText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InfoUserText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InfoPassText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        isAdminCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        InfoIDText = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PassText = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        PassTextAgain = new javax.swing.JPasswordField();
        isAdminCheck = new javax.swing.JCheckBox();
        UserText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        TableUser.setAutoCreateRowSorter(true);
        TableUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TableUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        TableUser.setForeground(new java.awt.Color(102, 102, 102));
        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "User", "Password", "isAdmin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableUser.setShowHorizontalLines(false);
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TableUserMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableUserMouseReleased(evt);
            }
        });
        TableUser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TableUserInputMethodTextChanged(evt);
            }
        });
        TableUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableUserKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TableUser);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DANH SÁCH TÀI KHOẢN ĐĂNG NHẬP");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NHẬP USER TÌM KIẾM:");

        FindText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindTextActionPerformed(evt);
            }
        });
        FindText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FindTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FindTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FindText))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FindText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THÔNG TIN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("USER");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("PASSWORD");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("IsAdmin");

        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UpdateButton.setText("CẬP NHẬT");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        isAdminCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isAdminCheckBox.setText("Is Admin");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("ID");

        InfoIDText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InfoIDText.setText("0");

        delButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delButton.setText("XÓA");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isAdminCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InfoPassText)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InfoIDText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InfoUserText))
                            .addComponent(delButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isAdminCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delButton)
                .addGap(84, 84, 84))
        );

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("TÀI KHOẢN");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("MẬT KHẨU");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("NHẬP LẠI MẬT KHẨU");

        isAdminCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isAdminCheck.setText("ADMIN");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("THÊM THÔNG TIN");

        addButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addButton.setText("THÊM");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PassTextAgain)
                            .addComponent(UserText)
                            .addComponent(PassText)
                            .addComponent(isAdminCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserText, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassText, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassTextAgain, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isAdminCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    //nút xóa
    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();
        
        int id = Integer.parseInt(InfoIDText.getText());
        new DanhSachTK().DeleteUser(id);        
        RefreshFormInfor();
        RefreshTable();
        new DanhSachTK().getInstance().RefreshListSQL();
        
    }//GEN-LAST:event_delButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String user = UserText.getText();
        String pass = PassText.getText();
        String passAgain = PassTextAgain.getText();
        if (user.equals("") || pass.equals("") || passAgain.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Không được bỏ trống bất cứ thông tin nào.", "Thông báo",  JOptionPane.ERROR_MESSAGE);
        }
        else if (!new DanhSachTK().getInstance().isExists(user)) 
        {
            if (pass.equals(passAgain))
            {            
                new DanhSachTK().getInstance().AddUser(user, pass, isAdminCheck.isSelected());    
                RefreshFormInput();
                RefreshTable();

            }
            else JOptionPane.showMessageDialog(null, "Mật khảu không khớp!", "Thông báo",  JOptionPane.ERROR_MESSAGE);
        }
        else JOptionPane.showMessageDialog(null, "Tên tài khoản đã có người dùng!", "Thông báo",  JOptionPane.ERROR_MESSAGE);

        
        
    }//GEN-LAST:event_addButtonActionPerformed

    //xử lý sự kiện khi click chuột trong jtable
    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        // TODO add your handling code here:        

    }//GEN-LAST:event_TableUserMouseClicked

   
        
    //xử lý sự kiện khi nhấn phím trong jtable
    private void TableUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableUserKeyPressed
        
        
        
    }//GEN-LAST:event_TableUserKeyPressed

    private void TableUserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TableUserInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TableUserInputMethodTextChanged

    private void TableUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseExited
        int id = new DanhSachTK().getInstance().getDanhSachTK().size() -1;
        getInstance().AddTable(id, new DanhSachTK().getInstance().getDanhSachTK().get(id).getUser(), new DanhSachTK().getInstance().getDanhSachTK().get(id).getPassword(), new DanhSachTK().getInstance().getDanhSachTK().get(id).getIsAdmin());
    }//GEN-LAST:event_TableUserMouseExited

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        
        int idupdate = Integer.parseInt(InfoIDText.getText()) ;
        String user = InfoUserText.getText();
        String pass = InfoPassText.getText();
        System.out.println(isAdminCheckBox.isSelected());
        
        new DanhSachTK().getInstance().ThayDoiInfo(idupdate, user, pass, isAdminCheckBox.isSelected());
        RefreshTable();
    }//GEN-LAST:event_UpdateButtonActionPerformed
    
    //hàm xử lý khi bấm phím xuống
    private void FindTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindTextKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_FindTextKeyPressed

    //hàm xử lý khi thả phím (tìm kiếm)
    private void FindTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindTextKeyReleased
        // TODO add your handling code here:
        
        String userFind= FindText.getText();
        System.out.println(userFind);
        if (!userFind.equals(""))
        {     
            ClearTable();
            for (int i=0; i< new DanhSachTK().getInstance().getDanhSachTK().size();i++)
            {
                if (new DanhSachTK().getInstance().getDanhSachTK().get(i).getUser().indexOf(userFind) != -1)
                {        
                    String user = new DanhSachTK().getInstance().DanhSachTK.get(i).getUser();
                    String pass = new DanhSachTK().getInstance().DanhSachTK.get(i).getPassword();
                    Boolean isadmin = new DanhSachTK().getInstance().DanhSachTK.get(i).getIsAdmin();
                    AddTable(i, user, pass, isadmin);
                }
            }
        }
        else
        {
            RefreshTable();
        }  
    }//GEN-LAST:event_FindTextKeyReleased

    //xử lý sự kiện khi thả chuột
    private void TableUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();

        int n = TableUser.getSelectedRow();
        String id = model.getValueAt(n, 0).toString();
        String user = model.getValueAt(n, 1).toString();
        String pass = TableUser.getValueAt(n, 2).toString();
        String isadmin=  TableUser.getValueAt(n, 3).toString();
                
        InfoIDText.setText(String.valueOf(id));
        InfoUserText.setText(user);
        InfoPassText.setText(pass);
        isAdminCheckBox.setSelected(Boolean.valueOf(isadmin));
    }//GEN-LAST:event_TableUserMouseReleased

    //xử lý sự kiện khi thả phím
    private void TableUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableUserKeyReleased

        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();

        int n = TableUser.getSelectedRow();
        String id = model.getValueAt(n, 0).toString();
        String user = model.getValueAt(n, 1).toString();
        String pass = TableUser.getValueAt(n, 2).toString();
        String isadmin=  TableUser.getValueAt(n, 3).toString();
        
        InfoIDText.setText(String.valueOf(id));
        InfoUserText.setText(user);
        InfoPassText.setText(pass);
        isAdminCheckBox.setSelected(Boolean.valueOf(isadmin));
    }//GEN-LAST:event_TableUserKeyReleased

    private void FindTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindTextActionPerformed


    
    //load data vào table
    public void LoadTable()
    {
        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();
        
        TableUser.setModel(model);       
        for (int i=0; i< new DanhSachTK().getInstance().DanhSachTK.size(); i++)
        {
            String user = new DanhSachTK().getInstance().DanhSachTK.get(i).getUser();
            String pass = new DanhSachTK().getInstance().DanhSachTK.get(i).getPassword();
            Boolean isadmin = new DanhSachTK().getInstance().DanhSachTK.get(i).getIsAdmin();
            
            AddTable(i,user, pass, isadmin);
        }
    }
    
    public void AddTable(int id,String user,String pass,Boolean isAdmin)
    {
        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();
        
        TableUser.setModel(model); 
        Object[] row = {id,user,pass,isAdmin};
            
        model.addRow(row);
    }
    
    public void ClearTable()
    {
        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();

        while (model.getRowCount() != 0)
        {
            model.removeRow(0);

        }
    }
    
    public void RefreshTable()
    {
        ClearTable();
        LoadTable();
    }
    
    
    
    public void SaveData()
    {
        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();

        for (int i =0; i< TableUser.getRowCount();i++)
        {
            int id = (int) model.getValueAt(i, 0);
            String user = model.getValueAt(i, 1).toString();
            String pass = TableUser.getValueAt(i, 2).toString();
            String isadmin=  TableUser.getValueAt(i, 3).toString();

            new DanhSachTK().getInstance().ThayDoiInfo(id, user, pass, Boolean.valueOf(isadmin));
            
        }
    }
    
    void DoSomething()
    {
   
    }
    
    void RefreshFormInfor()
    {
        InfoIDText.setText(String.valueOf(""));
        InfoUserText.setText("");
        InfoPassText.setText("");
        isAdminCheckBox.setSelected(false);
    }
    
    void RefreshFormInput()
    {
        UserText.setText("");
        PassText.setText("");
        PassTextAgain.setText("");
        isAdminCheck.setSelected(false);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FindText;
    private javax.swing.JLabel InfoIDText;
    private javax.swing.JTextField InfoPassText;
    private javax.swing.JTextField InfoUserText;
    private javax.swing.JPasswordField PassText;
    private javax.swing.JPasswordField PassTextAgain;
    public javax.swing.JTable TableUser;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UserText;
    private javax.swing.JButton addButton;
    private javax.swing.JButton delButton;
    private javax.swing.JCheckBox isAdminCheck;
    private javax.swing.JCheckBox isAdminCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
