/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;

import Main.Login;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Setup extends javax.swing.JFrame {
File data = new File("Data.dat");
    /**
     * Creates new form Setup
     */
    public Setup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JTextField();
        PASS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CÀI ĐẶT CƠ SỞ DỮ LIỆU");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("LOGIN:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PASSWORD:");

        PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NHẬP THÔNG TIN ĐĂNG NHẬP SQL SERVER");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PASS, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String Login = LOGIN.getText();
            String Pass = PASS.getText();   
            try {
                String URL = "jdbc:sqlserver://127.0.0.1:1433;";
                Connection con = DriverManager.getConnection(URL, Login, Pass);
                String SQL = "CREATE DATABASE "+ new DBConnect().getInstance().DBname+";";
                Statement st = con.createStatement();
                st.execute(SQL);
                st.execute(ScriptSetup());
                File data = new File("Data.dat");
                data.createNewFile();
                FileWriter fo = new FileWriter(data);
                fo.write(Login+"\n");
                fo.write(Pass);
                fo.close();
                JOptionPane.showMessageDialog(null, "Cài đặt cơ sở dữ liệu thành công!\nThông tin tài khoản đăng nhập:\nUSERNAME: ad\nPASSWORD: ad\nVui lòng mở lại chương trình để sử dụng.", "Thông báo",  JOptionPane.INFORMATION_MESSAGE);                  
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Cài đặt thất bại!", "Thông báo",  JOptionPane.ERROR_MESSAGE);   
            }      
           dispose();          
        } catch (IOException ex) {
            Logger.getLogger(Setup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //kiểm tra lần chạy đầu tiên (đã có file data chưa)
        File data = new File("Data.dat");
        if (data.exists())
        {
            new Login().show();
            return;
        }
            
        
        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setup().setVisible(true);
            }
        });
    }    
   
    String ScriptSetup()
    {
        return "USE ["+new DBConnect().getInstance().DBname+"]\n" +
        "SET ANSI_NULLS ON\n" +
        "SET QUOTED_IDENTIFIER ON\n" +
        "CREATE TABLE [dbo].[NhaCungCap](\n" +
        "	[MaNCC] [nchar](5) NOT NULL,\n" +
        "	[TenNCC] [nvarchar](32) NOT NULL,\n" +
        "	[DiaChi] [nvarchar](32) NULL,\n" +
        "	[SDT] [nvarchar](13) NULL,\n" +
        "PRIMARY KEY CLUSTERED \n" +
        "(\n" +
        "	[MaNCC] ASC\n" +
        ")WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\n" +
        ") ON [PRIMARY]\n" +
        "\n" +
        "SET ANSI_NULLS ON\n" +
        "SET QUOTED_IDENTIFIER ON\n" +
        "CREATE TABLE [dbo].[NhanVien](\n" +
        "	[TenNhanVien] [nvarchar](32) NOT NULL,\n" +
        "	[DiaChi] [nvarchar](32) NULL,\n" +
        "	[SDT] [nvarchar](13) NULL,\n" +
        "	[CMND] [nvarchar](15) NOT NULL,\n" +
        "	[NgayVaoLam] [date] NOT NULL,\n" +
        " CONSTRAINT [PK__NhanVien__77B2CA47D392610C] PRIMARY KEY CLUSTERED \n" +
        "(\n" +
        "	[CMND] ASC\n" +
        ")WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\n" +
        ") ON [PRIMARY]\n" +
        "\n" +
        "SET ANSI_NULLS ON\n" +
        "SET QUOTED_IDENTIFIER ON\n" +
        "CREATE TABLE [dbo].[PhieuNhap](\n" +
        "	[MaPhieuNhap] [nchar](5) NOT NULL,\n" +
        "	[MaSanPham] [nchar](5) NOT NULL,\n" +
        "	[SoLuong] [int] NOT NULL,\n" +
        "	[NgayLap] [date] NOT NULL,\n" +
        "	[CMND_NhanVien] [nvarchar](15) NOT NULL,\n" +
        "	[MaNhaCungCap] [nchar](5) NOT NULL,\n" +
        " CONSTRAINT [PK__PhieuNha__835ED13B2E8D8A5E] PRIMARY KEY CLUSTERED \n" +
        "(\n" +
        "	[MaPhieuNhap] ASC\n" +
        ")WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\n" +
        ") ON [PRIMARY]\n" +
        "\n" +
        "SET ANSI_NULLS ON\n" +
        "SET QUOTED_IDENTIFIER ON\n" +
        "CREATE TABLE [dbo].[SanPham](\n" +
        "	[MaSP] [nchar](5) NOT NULL,\n" +
        "	[TenSP] [nvarchar](32) NOT NULL,\n" +
        "	[SoLuong] [int] NULL,\n" +
        "	[LoaiSanPham] [nvarchar](32) NOT NULL,\n" +
        "	[GiaTien] [int] NOT NULL,\n" +
        "	[DonViTinh] [nvarchar](32) NULL,\n" +
        " CONSTRAINT [PK__SanPham__2725081CDFBB7381] PRIMARY KEY CLUSTERED \n" +
        "(\n" +
        "	[MaSP] ASC\n" +
        ")WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\n" +
        ") ON [PRIMARY]\n" +
        "\n" +
        "SET ANSI_NULLS ON\n" +
        "SET QUOTED_IDENTIFIER ON\n" +
        "SET ANSI_PADDING ON\n" +
        "CREATE TABLE [dbo].[TaiKhoanDangNhap](\n" +
        "	[id] [int] NOT NULL,\n" +
        "	[m_User] [varchar](20) NOT NULL,\n" +
        "	[m_Password] [varchar](20) NOT NULL,\n" +
        "	[isAdmin] [bit] NOT NULL,\n" +
        " CONSTRAINT [PK_TaiKhoanDangNhap] PRIMARY KEY CLUSTERED \n" +
        "(\n" +
        "	[id] ASC\n" +
        ")WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\n" +
        ") ON [PRIMARY]\n" +
        "\n" +
        "SET ANSI_PADDING OFF\n" +
        "ALTER TABLE [dbo].[PhieuNhap] ADD  CONSTRAINT [DF__PhieuNhap__NgayL__4B7734FF]  DEFAULT (getdate()) FOR [NgayLap]\n" +
        "ALTER TABLE [dbo].[SanPham] ADD  CONSTRAINT [DF__SanPham__DonViTi__41EDCAC5]  DEFAULT ('Cai') FOR [DonViTinh]\n" +
        "ALTER TABLE [dbo].[TaiKhoanDangNhap] ADD  CONSTRAINT [DF__TaiKhoanD__isAdm__5AB9788F]  DEFAULT ((0)) FOR [isAdmin]\n" +
        "ALTER TABLE [dbo].[PhieuNhap]  WITH CHECK ADD  CONSTRAINT [FK__PhieuNhap__MaNha__4E53A1AA] FOREIGN KEY([MaNhaCungCap])\n" +
        "REFERENCES [dbo].[NhaCungCap] ([MaNCC])\n" +
        "ALTER TABLE [dbo].[PhieuNhap] CHECK CONSTRAINT [FK__PhieuNhap__MaNha__4E53A1AA]\n" +
        "ALTER TABLE [dbo].[PhieuNhap]  WITH CHECK ADD  CONSTRAINT [FK__PhieuNhap__MaSP__4C6B5938] FOREIGN KEY([MaSanPham])\n" +
        "REFERENCES [dbo].[SanPham] ([MaSP])\n" +
        "ALTER TABLE [dbo].[PhieuNhap] CHECK CONSTRAINT [FK__PhieuNhap__MaSP__4C6B5938]\n" +
        "ALTER TABLE [dbo].[PhieuNhap]  WITH CHECK ADD  CONSTRAINT [FK_PhieuNhap_NhanVien] FOREIGN KEY([CMND_NhanVien])\n" +
        "REFERENCES [dbo].[NhanVien] ([CMND])\n" +
        "ALTER TABLE [dbo].[PhieuNhap] CHECK CONSTRAINT [FK_PhieuNhap_NhanVien]\n"+
        "insert into TaiKhoanDangNhap(id,m_User,m_Password,isAdmin) values (0,'ad','ad','true');";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LOGIN;
    private javax.swing.JTextField PASS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}